// Function to load cities from local storage
export function loadCities() {
  const storedCities = localStorage.getItem("cities");
  if (storedCities) {
    const parsedCities = JSON.parse(storedCities);
    // Check if parsedCities is an empty array
    if (Array.isArray(parsedCities) && parsedCities.length === 0) {
      return getDefaultCities(); // Function to return default cities list
    } else {
      return parsedCities;
    }
  } else {
    return getDefaultCities(); // Return default cities list if localStorage item is empty or null
  }
}

function getDefaultCities() {
  return [
    {
      name: "San Francisco",
      offset: -7,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "America/Los_Angeles",
    },
    {
      name: "New York",
      offset: -4,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "America/New_York",
    },
    {
      name: "London",
      offset: 1,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "Europe/London",
    },
    {
      name: "Dubai",
      offset: 4,
      isMarket: false,
      isAffectedByDST: false,
      timeZoneString: "Asia/Dubai",
    },
    {
      name: "Singapore",
      offset: 8,
      isMarket: false,
      isAffectedByDST: false,
      timeZoneString: "Asia/Singapore",
    },
    {
      name: "Tokyo",
      offset: 9,
      isMarket: false,
      isAffectedByDST: false,
      timeZoneString: "Asia/Tokyo",
    },
    {
      name: "Berlin",
      offset: 2,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "Europe/Berlin",
    },
    {
      name: "Paris",
      offset: 2,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "Europe/Paris",
    },
    {
      name: "Toronto",
      offset: -4,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "America/Toronto",
    },
    {
      name: "Seattle",
      offset: -7,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "America/Los_Angeles",
    },
    {
      name: "Los Angeles",
      offset: -7,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "America/Los_Angeles",
    },
    {
      name: "Boston",
      offset: -4,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "America/New_York",
    },
    {
      name: "Montreal",
      offset: -4,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "America/Toronto",
    },
    {
      name: "Washington D.C.",
      offset: -4,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "America/New_York",
    },
    {
      name: "Atlanta",
      offset: -4,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "America/New_York",
    },
    {
      name: "Austin",
      offset: -5,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "America/Chicago",
    },
    {
      name: "Chicago",
      offset: -5,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "America/Chicago",
    },
    {
      name: "Vancouver",
      offset: -7,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "America/Vancouver",
    },
    {
      name: "Dublin",
      offset: 1,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "Europe/Dublin",
    },
    {
      name: "Amsterdam",
      offset: 2,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "Europe/Amsterdam",
    },
    {
      name: "Zurich",
      offset: 2,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "Europe/Zurich",
    },
    {
      name: "Stockholm",
      offset: 2,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "Europe/Stockholm",
    },
    {
      name: "Madrid",
      offset: 2,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "Europe/Madrid",
    },
    {
      name: "Seoul",
      offset: 9,
      isMarket: false,
      isAffectedByDST: false,
      timeZoneString: "Asia/Seoul",
    },
    {
      name: "Hong Kong",
      offset: 8,
      isMarket: false,
      isAffectedByDST: false,
      timeZoneString: "Asia/Hong_Kong",
    },
    {
      name: "Sydney",
      offset: 10,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "Australia/Sydney",
    },
    {
      name: "Melbourne",
      offset: 10,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "Australia/Melbourne",
    },
    {
      name: "Wellington",
      offset: 12,
      isMarket: false,
      isAffectedByDST: true,
      timeZoneString: "Pacific/Auckland",
    },
    {
      name: "New York Stock Exchange (NYSE)",
      offset: -4,
      marketCap: 25.0,
      openTime: "09:30",
      closeTime: "16:00",
      isMarket: true,
      isAffectedByDST: true,
      timeZoneString: "America/New_York",
    },
    {
      name: "NASDAQ",
      offset: -4,
      marketCap: 21.7,
      openTime: "09:30",
      closeTime: "16:00",
      isMarket: true,
      isAffectedByDST: true,
      timeZoneString: "America/New_York",
    },
    {
      name: "Euronext (ENX)",
      offset: 1,
      marketCap: 7.2,
      openTime: "09:00",
      closeTime: "17:30",
      isMarket: true,
      isAffectedByDST: true,
      timeZoneString: "Europe/Amsterdam",
    },
    {
      name: "Shanghai Stock Exchange (SSE)",
      offset: 8,
      marketCap: 6.7,
      openTime: "09:30",
      closeTime: "15:00",
      isMarket: true,
      isAffectedByDST: false,
      timeZoneString: "Asia/Shanghai",
    },
    {
      name: "Tokyo Stock Exchange (TSE)",
      offset: 9,
      marketCap: 6.46,
      openTime: "09:00",
      closeTime: "15:00",
      isMarket: true,
      isAffectedByDST: false,
      timeZoneString: "Asia/Tokyo",
    },
    {
      name: "Shenzhen Stock Exchange (SZSE)",
      offset: 8,
      marketCap: 6.22,
      openTime: "09:30",
      closeTime: "15:00",
      isMarket: true,
      isAffectedByDST: false,
      timeZoneString: "Asia/Shanghai",
    },
    {
      name: "Bombay Stock Exchange (BSE)",
      offset: 5.5,
      marketCap: 5.1,
      openTime: "09:15",
      closeTime: "15:30",
      isMarket: true,
      isAffectedByDST: false,
      timeZoneString: "Asia/Kolkata",
    },
    {
      name: "National Stock Exchange of India (NSE)",
      offset: 5.5,
      marketCap: 5.01,
      openTime: "09:15",
      closeTime: "15:30",
      isMarket: true,
      isAffectedByDST: false,
      timeZoneString: "Asia/Kolkata",
    },
    {
      name: "Hong Kong Stock Exchange (HKEX)",
      offset: 8,
      marketCap: 3.98,
      openTime: "09:30",
      closeTime: "16:00",
      isMarket: true,
      isAffectedByDST: false,
      timeZoneString: "Asia/Hong_Kong",
    },
    {
      name: "Toronto Stock Exchange (TSX)",
      offset: -5,
      marketCap: 3.26,
      openTime: "09:30",
      closeTime: "16:00",
      isMarket: true,
      isAffectedByDST: true,
      timeZoneString: "America/Toronto",
    },
    {
      name: "London Stock Exchange (LSE)",
      offset: 0,
      marketCap: 3.18,
      openTime: "08:00",
      closeTime: "16:30",
      isMarket: true,
      isAffectedByDST: true,
      timeZoneString: "Europe/London",
    },
    {
      name: "Saudi Stock Exchange (TADAWUL)",
      offset: 3,
      marketCap: 2.71,
      openTime: "10:00",
      closeTime: "15:00",
      isMarket: true,
      isAffectedByDST: false,
      timeZoneString: "Asia/Riyadh",
    },
    {
      name: "German Stock Exchange (XETRA)",
      offset: 1,
      marketCap: 2.37,
      openTime: "08:00",
      closeTime: "17:30",
      isMarket: true,
      isAffectedByDST: true,
      timeZoneString: "Europe/Berlin",
    },
    {
      name: "SIX Swiss Exchange (SIX)",
      offset: 1,
      marketCap: 1.95,
      openTime: "09:00",
      closeTime: "17:30",
      isMarket: true,
      isAffectedByDST: true,
      timeZoneString: "Europe/Zurich",
    },
    {
      name: "Nasdaq Nordic and Baltic Exchanges (OMX)",
      offset: 1,
      marketCap: 1.94,
      openTime: "09:00",
      closeTime: "17:00",
      isMarket: true,
      isAffectedByDST: true,
      timeZoneString: "Europe/Stockholm",
    },
    {
      name: "Korea Exchange (KRX)",
      offset: 9,
      marketCap: 1.83,
      openTime: "09:00",
      closeTime: "15:30",
      isMarket: true,
      isAffectedByDST: false,
      timeZoneString: "Asia/Seoul",
    },
    {
      name: "Taiwan Stock Exchange (TWSE)",
      offset: 8,
      marketCap: 1.59,
      openTime: "09:00",
      closeTime: "13:30",
      isMarket: true,
      isAffectedByDST: false,
      timeZoneString: "Asia/Taipei",
    },
    {
      name: "Australian Securities Exchange (ASX)",
      offset: 10,
      marketCap: 1.55,
      openTime: "10:00",
      closeTime: "16:00",
      isMarket: true,
      isAffectedByDST: true,
      timeZoneString: "Australia/Sydney",
    },
    {
      name: "Johannesburg Stock Exchange (JSE)",
      offset: 2,
      marketCap: 1.36,
      openTime: "09:00",
      closeTime: "17:00",
      isMarket: true,
      isAffectedByDST: true,
      timeZoneString: "Africa/Johannesburg",
    },
    {
      name: "Tehran Stock Exchange (TSE)",
      offset: 3.5,
      marketCap: 1.29,
      openTime: "09:30",
      closeTime: "15:30",
      isMarket: true,
      isAffectedByDST: false,
      timeZoneString: "Asia/Tehran",
    },
  ];
}
